# indexing dari belakang atau index(-)
print("="*45)
print("indexing menggunakan mines".upper().center(45))
print("="*45)
print(f"index ke-(-2) dari list\n {list1} adalah {list1[-2]}\n")
print(f"index ke-(-1) dari list\n {list1} adalah {list1[-1]}\n")